before_script:
  - apt-get update -qq
  - apt-get -y -qq install libhidapi-dev libcap-dev
  - wget https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux -O opam-2.0.1-x86_64-linux
  - mkdir ~/opam-bin
  - mv opam-2.0.1-x86_64-linux ~/opam-bin/opam
  - export PATH="$HOME/opam-bin/opam${PATH:+:}${PATH:-}"
  - opam init
  - opam repository add jgb https://gitlab.com/gabriel.alfour/tezos-opam-repository.git
  - eval $(opam env)

default-job:
  script:
    - opam install --working-dir .
  artifacts:
    paths:
      - parser.exe
