before_script:
  - apt-get update -qq
  - apt-get -y -qq install libhidapi-dev libcap-dev
  - wget https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux -O opam-2.0.1-x86_64-linux
  - mkdir ~/opam-bin
  - mv opam-2.0.1-x86_64-linux ~/opam-bin/opam
  - chmod +x ~/opam-bin/opam
  - export PATH="$HOME/opam-bin/opam${PATH:+:}${PATH:-}"
  - echo "$PATH"
  - ~/opam-bin/opam init
  - eval $(~/opam-bin/opam env)
  - ~/opam-bin/opam repository add jgb https://gitlab.com/gabriel.alfour/tezos-opam-repository.git
  - eval $(~/opam-bin/opam env)

default-job:
  script:
    - ~/opam-bin/opam install --working-dir .
    - opam --version
  artifacts:
    paths:
      - parser.exe
