name: ligo-squirrel

dependencies:
  - async
  - base
  - bytestring
  - containers
  - data-default
  - duplo
  - exceptions
  - fastsum
  - filepath
  - ghc-prim
  - hashable
  - interpolate
  - mtl
  - pretty
  - sorted-list
  - text
  - transformers
  - tree-sitter

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options: -freverse-errors -Wall -Werror

library:
  source-dirs:
    - src/

  include-dirs:
    - grammar/pascaligo
    - grammar/reasonligo
    - grammar/camligo
    - grammar/pascaligo/src
    - grammar/reasonligo/src
    - grammar/camligo/src

  c-sources:
    - grammar/pascaligo/src/parser.c
    - grammar/reasonligo/src/parser.c
    - grammar/camligo/src/parser.c

  dependencies:
    - haskell-lsp-types
    - aeson
    - process
    - lens
    - lens-aeson
    - bytestring
    - unordered-containers

executables:
  ligo-squirrel:
    main: Main.hs

    dependencies:
      - haskell-lsp
      - hslogger
      - interpolate
      - lens
      - lens-aeson
      - ligo-squirrel
      - directory
      - unix
      - stm
      - ttrie

    source-dirs:
      - app/ligo-squirrel

    ghc-options: -threaded -Werror

  ligo-vet:
    main: Main.hs

    other-modules: []

    source-dirs:
      - app/ligo-vet

    dependencies:
      - ligo-squirrel
      - optparse-applicative
      - with-utf8

tests:
  squirrel-test:
    main: Driver.hs

    source-dirs:
      - test/

    dependencies:
      - HUnit
      - directory
      - filepath
      - hspec-expectations
      - ligo-squirrel
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hunit
