# This file contains pipeline configuration used by Serokell at https://gitlab.com/serokell/ligo/ligo

stages:
  - tooling
  - push

default:
  tags: [nix]

# jobs for building and testing LSP
include: '/tools/lsp/.gitlab-ci.yml'

# publish vscode extension to the extension marketplace
vscode-extension-publish:
  stage: push
  dependencies: [vscode-extension]
  only: [vscode-production]
  when: manual
  script:
    - nix run -f nix/vsce.nix -c vsce publish --packagePath *.vsix -p "$MICROSOFT_MARKETPLACE_TOKEN"

# publish docker image for lsp to the gitlab registry
lsp-docker-image-publish:
  stage: push
  only: [tooling]
  script:
    # set creation date to current date
    - CURRENT_DATE=$(date --iso-8601=seconds)
    - nix-build tools/lsp -A lsp-docker-image --argstr creationDate "$CURRENT_DATE"
    # docker registry credentials provided by gitlab
    - DEST_CREDS="$CI_REGISTRY_USER":"$CI_REGISTRY_PASSWORD"
    # use '--insecury-policy' to disable container signature checking, because we only upload the image
    - nix run -f tools/lsp skopeo -c
        skopeo --insecure-policy copy --dest-creds "$DEST_CREDS" docker-archive:./result docker://"$CI_REGISTRY_IMAGE"/ligo-lsp:latest
